### ISSUE TITLE
Version metadata not updated for 0.6.2

### ISSUE THREAD

**Issue by Samsagax** [flathub/org.supertuxproject.SuperTux#11]
As is stated in #9 the json file is already modified, but the flathub build bot didn´t pick it up. Is it possible to request a build for this game [here](https://flathub.org/builds/#/)?

**Comment by hfiguiere** [comment]
What let you think it is not 0.6.2?

It show 0.6.2 when I launch it.

**Comment by Samsagax** [comment]
In the [flathub page](https://www.flathub.org/apps/details/org.supertuxproject.SuperTux) it appears to be 0.6.1. But in-game it shows v0.6.2. It's weird.

**Comment by hfiguiere** [comment]
likely the metadata upstream wasn't updated.

**Comment by Samsagax** [comment]
Then disregard my report. But I think as I was misled, others would be too. Maybe you should reach flathub to correct that metadata.

Thanks and sorry for bothering you.

**Comment by hfiguiere** [comment]
@Samsagax No worries, it's a valid issue (and fixed now)
