### ISSUE TITLE
No GPU acceleration enabled

### ISSUE THREAD

**Issue by mooreye** [flathub/org.supertuxproject.SuperTux#19]

**Comment by Alexander-Wilms** [comment]
Sine it has the permission "--device=all", GPU acceleration should work.

**Comment by mooreye** [comment]
> Sine it has the permission "--device=all", GPU acceleration should work.

Nevermind then, it was an issue with my overrides. Still, why does it need ALL device access?

**Comment by Newbytee** [comment]
> > Sine it has the permission "--device=all", GPU acceleration should work.
> 
> Nevermind then, it was an issue with my overrides. Still, why does it need ALL device access?

Controllers, I think.
