### ISSUE TITLE
No Joystick support with Flatpak version

### ISSUE THREAD

**Issue by xalmat** [flathub/org.supertuxproject.SuperTux#2]
I'm trying to play SuperTux 2 on my Kubuntu 18.04 install using the Flatpak version. However, it does not detect my Joysticks properly (Specifically Xbox 360, Xbox One, and 8bitdo NES30 Pro). However, if I use the normal install from the Kubuntu repos, the joysticks work just fine.

**Comment by Alexander-Wilms** [comment]
Does it work if you run `flatpak run 
--device=all org.supertuxproject.SuperTux` ?

**Comment by xalmat** [comment]
It does!
Must be one of those weird esoteric things about flatpak they don't tell users about.

**Comment by Alexander-Wilms** [comment]
That's just the sandboxing.
