### ISSUE TITLE
Flathub lists Supertux as a proprietary app

### ISSUE THREAD

**Issue by 1bcb** [flathub/org.supertuxproject.SuperTux#20]
The Flathub page incorrectly says this is a proprietary app.

**Comment by AsciiWolf** [comment]
The _project_license_ entry in AppStream metadata looks correct: https://github.com/SuperTux/supertux/blob/master/supertux2.appdata.xml#L5

**Comment by Alexander-Wilms** [comment]
Maybe the fact that `project_license` contains two licenses causes the issue?

**Comment by AsciiWolf** [comment]
This should be valid, see the [documentation](https://freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-project_license).

**Comment by Zishan-Rahman** [comment]
> The _project_license_ entry in AppStream metadata looks correct: https://github.com/SuperTux/supertux/blob/master/supertux2.appdata.xml#L5

The problem _here_ is that `GPL-3.0+` should be `GPL-3.0-or-later`. I recently opened [a PR here](https://github.com/flathub/org.supertuxproject.SuperTux/pull/22) that addresses this (as well as updating the Freedesktop runtime).

**Comment by tibequadorian** [comment]
FYI it's still listed as proprietary

**Comment by Zishan-Rahman** [comment]
> FYI it's still listed as proprietary

Yeah, it is. I don't know why this is happening. I just installed the Flatpak to see if the appdata.xml patch I made was applied to it, and it _was_. So it **should** be showing the correct licenses on Flathub too, but it isn't, and I can't figure out why.

**Comment by Alexander-Wilms** [comment]
I guess it's because the metainfo file is not valid, so maybe an older version keeps getting used?

```
$ flatpak run org.freedesktop.appstream.cli validate /var/lib/flatpak/app/org.supertuxproject.SuperTux/x86_64/stable/active/export/share/metainfoorg.supertuxproject.SuperTux.appdata.xml
I: org.supertuxproject.SuperTux:27: url-not-secure http://supertux.lethargik.org/
E: org.supertuxproject.SuperTux:35: screenshot-no-media
E: org.supertuxproject.SuperTux:36: screenshot-no-media
E: org.supertuxproject.SuperTux:37: screenshot-no-media
E: org.supertuxproject.SuperTux:38: screenshot-no-media
E: org.supertuxproject.SuperTux:39: screenshot-no-media

? Validation failed: errors: 5, infos: 1, pedantic: 6
```

**Comment by Zishan-Rahman** [comment]
> I guess it's because the metainfo file is not valid, so maybe an older version keeps getting used?
> 
> ```
> $ flatpak run org.freedesktop.appstream.cli validate /var/lib/flatpak/app/org.supertuxproject.SuperTux/x86_64/stable/active/export/share/metainfoorg.supertuxproject.SuperTux.appdata.xml
> I: org.supertuxproject.SuperTux:27: url-not-secure http://supertux.lethargik.org/
> E: org.supertuxproject.SuperTux:35: screenshot-no-media
> E: org.supertuxproject.SuperTux:36: screenshot-no-media
> E: org.supertuxproject.SuperTux:37: screenshot-no-media
> E: org.supertuxproject.SuperTux:38: screenshot-no-media
> E: org.supertuxproject.SuperTux:39: screenshot-no-media
> 
> ? Validation failed: errors: 5, infos: 1, pedantic: 6
> ```
> 
> Cf. [SuperTux/supertux@25f165c](https://github.com/SuperTux/supertux/commit/25f165ce96d74e163a1afe6230de94469dee9ffc)

OK, I have an idea: I'll take [the latest revision of supertux2.appdata.xml on the SuperTux repository](https://github.com/SuperTux/supertux/blob/d9f8785cbdd4d6785dcb9f5908162f52d3e571f6/supertux2.appdata.xml), which includes both the license change and the changes mentioned here, and plug that in here somehow. I'll open a PR soon to take care of this.

**Comment by Zishan-Rahman** [comment]
> OK, I have an idea: I'll take [the latest revision of supertux2.appdata.xml on the SuperTux repository](https://github.com/SuperTux/supertux/blob/d9f8785cbdd4d6785dcb9f5908162f52d3e571f6/supertux2.appdata.xml), which includes both the license change and the changes mentioned here, and plug that in here somehow. I'll open a PR soon to take care of this.

[I just opened the PR.](https://github.com/flathub/org.supertuxproject.SuperTux/pull/23)

**Comment by Alexander-Wilms** [comment]
You should probably specify a commit or the build will break when it gets updated:

https://github.com/SuperTux/supertux/blob/12cf6c012e2bc1b91ef12fe56df1b169b2a5fa47/supertux2.appdata.xml

**Comment by Zishan-Rahman** [comment]
> You should probably specify a commit or the build will break when it gets updated:
> 
> https://github.com/SuperTux/supertux/blob/12cf6c012e2bc1b91ef12fe56df1b169b2a5fa47/supertux2.appdata.xml

Argh, I thought I copied the permalink, how on earth did I forget to do that? :man_facepalming:

**Comment by Zishan-Rahman** [comment]
I took care of that here: https://github.com/flathub/org.supertuxproject.SuperTux/pull/23/commits/caf3643b5f03aeebcc4c63dd3e5a73a68d56c8e3

**Comment by Zishan-Rahman** [comment]
> > OK, I have an idea: I'll take [the latest revision of supertux2.appdata.xml on the SuperTux repository](https://github.com/SuperTux/supertux/blob/d9f8785cbdd4d6785dcb9f5908162f52d3e571f6/supertux2.appdata.xml), which includes both the license change and the changes mentioned here, and plug that in here somehow. I'll open a PR soon to take care of this.
> 
> [I just opened the PR.](https://github.com/flathub/org.supertuxproject.SuperTux/pull/23)

Note that the PR now just modifies the appdata patch instead of downloading the new one. When the patch is applied, the contents of the appdata file there will match those of the latest revision of supertux2.appdata.xml in the SuperTux repository.

**Comment by Alexander-Wilms** [comment]
For some reason, it's still shown as proprietary.

**Comment by Zishan-Rahman** [comment]
> It's still being shown as proprietary, perhaps since the `project_license` tag contains CC-BY-SA-2.0.
> 
> Citing https://www.freedesktop.org/software/appstream/docs/chap-Metadata.html#tag-project_license:
> 
> > The license given in the project_license tag should be the ‘main’ license of the project. For a software project, this is typically the license for the code. It is not recommended to include the license for accompanying documentation (for example) in project_license, as that could confuse users. In particular, the CC-BY-SA-3.0 license which is commonly used for documentation is not an (FSF or OSI) approved license for free software, so including it in project_license results in the project as a whole being considered non-free.
> 
> However, `<project_license>GPL-3.0+ and CC-BY-SA-3.0</project_license>` is being displayed correctly:
> 
> https://github.com/flathub/org.gnome.Hamster/blob/ef11ba898d17335e53e4e0fbb3b279a22edda996/org.gnome.Hamster.metainfo.xml#L5C3-L5C63
> 
> https://flathub.org/apps/org.gnome.Hamster

[I took out "AND CC-BY-SA-2.0" from the appdata patch and opened a PR just now](https://github.com/flathub/org.supertuxproject.SuperTux/pull/24). I didn't change it to "AND CC-BY-SA-3.0" since I don't know _exactly_ how the CC-BY-SA-2.0 license applies to the SuperTux project, just that it does, according to supertux2.appdata.xml in the SuperTux repository. However, after doing a quick skim-read code search on GitHub, I found out that most (if not all) declared applications of CC-BY-SA there were of _at least_ version 3.0 (some were of version 4.0), so it _might_ be worth opening a discussion in the SuperTux repo to see if the 2.0 version of the license still applies to anywhere and anything I might be missing. If it isn't, then it could be changed there (and eventually here as well) to "CC-BY-SA-3.0", though we have to be completely sure of it first.

**Comment by Alexander-Wilms** [comment]
Now it's shown correctly:

![image](https://github.com/flathub/org.supertuxproject.SuperTux/assets/3226457/e507ccf2-2ec2-4810-8f25-3bdf8db5c4e8)

The license change had to be approved by the Flathub admins.
